exclude: 'docs|node_modules|migrations|.git|.tox'
default_stages: [commit]
fail_fast: true

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        files: (^|/)a/.+\.(py|html|sh|css|js)$
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

-   repo: https://github.com/asottile/reorder_python_imports
    rev: v3.12.0
    hooks:
      - id: reorder-python-imports

-   repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: flake8
        language: python
        types: [python]

-   repo: local
    hooks:
    -   id: pylint
        name: pylint
        entry: pylint
        language: python
        language_version: python3.11  # Replace with your Python version
        types: [python]

-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.6
    hooks:
    -   id: bandit
        args: ["-ll"]  # optional: only show warnings/errors of a certain level
    
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.7.1  # Use the ref you want to point at
    hooks:
    -   id: mypy

-   repo: local
    hooks:
    -   id: pytest
        name: pytest
        entry: pytest
        language: python
        types: [python]
