version: '3.9'

services:
  foodtruck:
    volumes:
      - ./static:/app/static
      - ./logs/gunicorn:/app/logs
    env_file:
      - .env.prod
    image: foodtruck-amd64:latest
    ports:
      - "8000:8000"
    depends_on:
      - db_food_trucks
    restart: unless-stopped
  db_food_trucks:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.db
    ports:
      - "5432:5432"
    restart: unless-stopped
volumes:
  postgres_data:
