# Generated by Django 5.0 on 2023-12-10 20:07

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FoodTruck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("applicant", models.CharField(max_length=100)),
                (
                    "facility_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("address", models.CharField(blank=True, max_length=500, null=True)),
                ("latitude", models.DecimalField(decimal_places=7, max_digits=10)),
                ("longitude", models.DecimalField(decimal_places=7, max_digits=10)),
                (
                    "food_items",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                ("status", models.CharField(blank=True, max_length=100, null=True)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "Food Trucks",
            },
        ),
    ]
