# Generated by Django 5.0 on 2023-12-10 20:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foodtruck",
            name="latitude",
            field=models.DecimalField(decimal_places=15, max_digits=18),
        ),
        migrations.AlterField(
            model_name="foodtruck",
            name="longitude",
            field=models.DecimalField(decimal_places=15, max_digits=18),
        ),
    ]
